# Generated by Django 5.1.4 on 2024-12-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('package', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=50)),
            ],
        ),
    ]
